image: maven:latest

stages:
    - build
    - test
    - release

build_compile:
  stage: build
  script:
    - mvn -B clean compile

build_assembly:
    stage: build
    script:
      - mvn assembly:single
    artifacts:
      name: "GeoJSON ZIP"
      paths:
        - ./target/geojson-export-1.0.0.zip

test:
    stage: test
    script: 
        - mvn -B clean test

release:
    stage: release
    image: registry.gitlab.com/gitlab-org/release-cli
    rules:
        - if: $CI_COMMIT_TAG
    script:
        - echo 'running release'
    release:
        name: 'Release $CI_COMMIT_TAG'
        description: 'Version $CI_COMMIT_TAG'
        tag_name: '$CI_COMMIT_TAG'
        ref: $CI_COMMIT_SHA
