image: maven:latest

stages:
    - build
    - test
    - release

build:
    stage: build
    script:
        - mvn -B package

test:
    stage: test
    script: 
        - mvn -B clean test

release:
    stage: release
    image: registry.gitlab.com/gitlab-org/release-cli
    rules:
        - if: $CI_COMMIT_TAG != ''
          when: always
        - when: never
    script:
        - release-cli create --name "Release $CI_COMMIT_TAG" --tag-name $CI_COMMIT_TAG --ref $CI_COMMIT_SHA
