image: maven:latest

stages:
    - build
    - test
    - release

variables:
    PACKAGE_VERSION: $CI_COMMIT_TAG
    DARWIN_AMD64_BINARY: "geojsonexport-darwin-amd64-${PACKAGE_VERSION}"
    LINUX_AMD64_BINARY: "geojsonexport-linux-amd64-${PACKAGE_VERSION}"
    PACKAGE_REGISTRY_URL: "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/geojsonexport/${PACKAGE_VERSION}"

build:
    stage: build
    script:
        - mkdir bin
        - mvn assembly:clean
    artifacts:
      paths:
        - bin/

test:
    stage: test
    script: 
        - mvn -B clean test

upload:
    stage: upload
    image: curlimages/curl:latest
    rules:
        - if: $CI_COMMIT_TAG
    script:
        - |
            curl --header "JOB-TOKEN: ${CI_JOB_TOKEN}" --upload-file bin/${DARWIN_AMD64_BINARY} ${PACKAGE_REGISTRY_URL}/${DARWIN_AMD64_BINARY}
        - |
            curl --header "JOB-TOKEN: ${CI_JOB_TOKEN}" --upload-file bin/${LINUX_AMD64_BINARY} ${PACKAGE_REGISTRY_URL}/${LINUX_AMD64_BINARY}

release:
    stage: release
    image: registry.gitlab.com/gitlab-org/release-cli
    rules:
        - if: $CI_COMMIT_TAG
    script:
        - |
            release-cli create --name "Release $CI_COMMIT_TAG" --tag-name $CI_COMMIT_TAG --description "Version $CI_COMMIT_TAG" \
              --assets-link "{\"name\":\"${DARWIN_AMD64_BINARY}\",\"url\":\"${PACKAGE_REGISTRY_URL}/${DARWIN_AMD64_BINARY}\"}" \
              --assets-link "{\"name\":\"${LINUX_AMD64_BINARY}\",\"url\":\"${PACKAGE_REGISTRY_URL}/${LINUX_AMD64_BINARY}\"}"
