image: maven:latest

stages:
    - build
    - test
    - release

build_compile:
  stage: build
  script:
    - mvn -B clean compile

artifacts:
    stage: build
    rules:
        - if: $CI_COMMIT_TAG
    script:
      - mvn assembly:single
      - echo "Building extension"
      - echo "${CI_JOB_ID}" > CI_JOB_ID.txt
    artifacts:
      paths:
        - target/geojson-export-1.0.0.zip
        - target/geojson-export-1.0.0.tgz
        - CI_JOB_ID.txt
      expire_in: never

test:
    stage: test
    script: 
        - mvn -B clean test

release:
    stage: release
    image: registry.gitlab.com/gitlab-org/release-cli
    rules:
        - if: $CI_COMMIT_TAG
    script:
      - |
        release-cli create --name "Release $CI_COMMIT_TAG" --tag-name $CI_COMMIT_TAG --description "Version $CI_COMMIT_TAG" \
          --assets-link "{\"name\":\"geojson-v1.0.0.zip\",\"url\":\"https://gitlab.com/labiangashi/geojson-export/-/jobs`cat CI_JOB_ID.txt`/artifacts/target/geojson-v1.0.0.zip\"}"

